# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{census}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mark Kendall"]
  s.date = %q{2010-04-05}
  s.description = %q{Census is a Rails plugin that collects searchable demographics data for each of your application's users.}
  s.email = %q{mark@envylabs.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/controllers/census/data_groups_controller.rb",
     "app/models/answer.rb",
     "app/models/boolean_question.rb",
     "app/models/choice.rb",
     "app/models/data_group.rb",
     "app/models/number_question.rb",
     "app/models/question.rb",
     "app/models/string_question.rb",
     "app/views/census/data_groups/_choice_fields.html.erb",
     "app/views/census/data_groups/_form.html.erb",
     "app/views/census/data_groups/_question_fields.html.erb",
     "app/views/census/data_groups/edit.html.erb",
     "app/views/census/data_groups/index.html.erb",
     "app/views/census/data_groups/new.html.erb",
     "config/routes.rb",
     "generators/census/USAGE",
     "generators/census/census_generator.rb",
     "generators/census/lib/insert_commands.rb",
     "generators/census/lib/rake_commands.rb",
     "generators/census/templates/README",
     "generators/census/templates/census.js",
     "generators/census/templates/migrations/census.rb",
     "generators/census/templates/migrations/create_users.rb",
     "generators/census/templates/user.rb",
     "lib/census.rb",
     "lib/census/user.rb"
  ]
  s.homepage = %q{http://github.com/envylabs/census}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Rails user demographics collection and searching}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<acts_as_list>, ["= 0.1.2"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<acts_as_list>, ["= 0.1.2"])
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<acts_as_list>, ["= 0.1.2"])
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

